### ISSUE TITLE
import to Android Studio while GitHub integrated

### ISSUE THREAD

**Issue by 7ShaYaN7** [darshan-/Battery-Indicator-Support#1]
Hi,
how to open the project in Android Studio and syncing with the GitHub repository at the same time?

as you know this project is not Gradle-based and if I want to import it, how to have version control abilities and syncing?

**Comment by darshan-** [comment]
I'm familiar with neither Android Studio nor Gradle.  I use emacs and ant.  It should work fine with Android Studio and Gradle; I'm just not able to offer support for doing so.
