### ISSUE TITLE
Way to donate without Google

### ISSUE THREAD

**Issue by yaomtc** [darshan-/Battery-Indicator-Support#15]
If someone wants to donate but does not have Google Play installed to purchase BatteryBot Pro, is there another way?

**Comment by TPS** [comment]
https://github.com/darshan-/Battery-Indicator-Support/blob/HEAD/PackageDownload.md#support--donate addresses this directly.

**Comment by yaomtc** [comment]
I see, while that page isn't linked in the app itself, it is linked on the F-Droid listings. That'll do! Thanks.
