### ISSUE TITLE
Feature Request: Battery Charging Limit

### ISSUE THREAD

**Issue by developersx3** [darshan-/Battery-Indicator-Support#6]
I've read a couple of posts on XDA(https://forum.xda-developers.com/v20/themes/battery-charge-limit-vs-magic-control-t3821395)], Reddit(https://www.reddit.com/r/LineageOS/comments/7t3tmh/battery_charge_limit/) and some other sites (google basically) and the general consensus appears to be that charging to 100% decreases the longevity of the battery and optimal charge is between 80-90%.

On a lot of android devices, the charge of a phone can be stopped at anypoint by updating the battery control file.  E.g: On my LGv20, /sys/class/power_supply/battery/charging_enabled is "1" when it is charging.  I can force a stop to it by setting the value to 0 thru adb command:
        `echo 0 > /sys/class/power_supply/battery/charging_enabled`

I've found applications that will allow you to add a charge limit.  Instead of adding yet another processes thats running to continually monitor battery and prevent charge after x%, I was wondering whether this can be an option included in as a feature in your app, since it is running anyway as a battery monitor.  Perhaps, additional option for the "alarm" setting to:

-    Stop charging after certain %
-    charging after it drops below % if its connected
-    Run a script or app below or above certain %

Thanks.

**Comment by darshan-** [comment]
That would be pretty cool, and this is a well written and well reasoned issue report.  But I'm not comfortable adding this feature.

- The particular file needed will vary from device to device, and may not be present on every device.  On my Pixel 2, I have `/sys/class/power_supply/battery/charge_disable`, which presumably works in the opposite way (setting it to `1` to disable charging).  I'm not sure, but my guess is that other variations are out there, so it wouldn't be feasible to support them all without regularly adding special cases.
- Root is required, at least on most devices.  (My Pixel 2 allows me to read the file, but not write to it.)  I have a policy of not adding features to this app that require root.

Thanks again for the report, and sorry to disappoint.
